// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    App: typeof import("./src/components/App.vue")["default"];
    Content: typeof import("./src/components/Content.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    Footer: typeof import("./src/components/Footer.vue")["default"];
    Links: typeof import("./src/components/nav/Links.vue")["default"];
    Logo: typeof import("./src/components/nav/Logo.vue")["default"];
    Menu: typeof import("./src/components/nav/Menu.vue")["default"];
    Nav: typeof import("./src/components/Nav.vue")["default"];
    NotFound: typeof import("./src/components/NotFound.vue")["default"];
    Search: typeof import("./src/components/nav/Search.vue")["default"];
    SearchContent: typeof import("./src/components/nav/SearchContent.vue")["default"];
    Sidebar: typeof import("./src/components/Sidebar.vue")["default"];
    Switch: typeof import("./src/components/common/Switch.vue")["default"];
    ThemeToggle: typeof import("./src/components/nav/ThemeToggle.vue")["default"];
  }
}
